### PR TITLE
[NoTicket] Set indentation to two spaces

### PR DESCRIPTION
**Pull request by matiasbeckerle**
# Background

Folks, as discussed previously we are going to use the two spaces indentation as standard. This PR aims to put every file into that convention.

# Changes

- Set indentation to two spaces.

# Notes

You are not going to find anything besides indentation changes.

### CODE REVIEW

**Comment by matiasbeckerle** [comment]
@AlphaGit I can't mention or add you as reviewer. Maybe your user is outside the org?

**Review by mravinale — APPROVED** [review]

**Review by juampick — APPROVED** [review]
Thanks

**Comment by AlphaGit** [comment]
@matiasbeckerle Weird. I am part of the organization, but maybe not in the groups that is a collaborator for the repo? I'll check it out.

**Comment by AlphaGit** [comment]
@matiasbeckerle I just checked, and I don't have admin access for this repository. I thought I did. I don't know how the permissions are set up, sorry.

Maybe @mravinale or @juampick can add me as a collaborator?

**Comment by juampick** [comment]
I have just added @AlphaGit 

Please check now

**Comment by AlphaGit** [comment]
@juampick Thanks! Yes, I can be added as a reviewer now. :)

**Pull request merged**
